-- CREATE TABLES BELOW
CREATE TABLE IF NOT EXISTS USERS( 
    USER_ID BIGINT NOT NULL PRIMARY KEY AUTO_INCREMENT, 
    USER_NAME VARCHAR(500) NOT NULL, 
    USER_DESCRIPTION VARCHAR(500) NOT NULL 
);
